apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  wait: true
  path: ./clusters/k3s/flux-system         # <— points to the PLAIN kustomize above
  sourceRef:
    kind: GitRepository
    name: flux-system
