apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  wait: true
  path: ./clusters/k3s-prod/apps      # <- points to the apps dir in *this* repo
  sourceRef:
    kind: GitRepository
    name: flux-system                  # created by flux bootstrap
  dependsOn:
    - name: flux-system                # optional, ensures controllers exist
