apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: langgraph
  namespace: langgraph
spec:
  interval: 5m
  chart:
    spec:
      chart: langgraph-dataplane        # check exact chart name in the repo index
      version: 0.2.6                    # pin a version; do NOT use "*"
      sourceRef:
        kind: HelmRepository
        name: langchain
        namespace: flux-system
      reconcileStrategy: ChartVersion
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    timeout: 10m
  valuesFrom:
    - kind: ConfigMap
      name: langgraph-values-common
      valuesKey: values.yaml
  values: {}

