apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: langgraph
  namespace: langgraph
spec:
  interval: 5m
  chart:
    spec:
      chart: langgraph-dataplane
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: langchain
        namespace: flux-system
      chart: langgraph-dataplane          # check the chart name in the index
      version: 0.1.1                      # pin a known-good chart version
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    timeout: 10m
  valuesFrom:
    - kind: ConfigMap
      name: langgraph-values-common
      valuesKey: values.yaml
  values: {}  # keep empty; use valuesFrom
